### PR TITLE
FIX: POST to route returns 404

### PR DESCRIPTION
**Pull request by AllSpeeds**
https://github.com/tommymessbauer/pipeline-router/issues/10

### CODE REVIEW

**Comment by panthershark** [comment]
I bet this allows the match event to fire more than once now, fires multiple handlers and opens up a race condition. 

We need a test for that anyways to avoid the regression.

**Comment by AllSpeeds** [comment]
How would you reproduce that? Are you going to write a test?

On Thursday, April 10, 2014, Tommy Messbauer notifications@github.com
wrote:

> I bet this allows the match event to fire more than once now, fires
> multiple handlers and opens up a race condition.
> 
> We need a test for that anyways to avoid the regression.
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/tommymessbauer/pipeline-router/pull/11#issuecomment-40159544
> .

## 

Chad Gowan

All Speeds Web Design & Development
Austin, TX
www: http://www.allspeeds.net
email: chad@allspeeds.net
ph: 512.924.7797

**Comment by AllSpeeds** [comment]
@tommymessbauer Do you want me to write a test for this?  I have an idea.  I'll add it to the PR.

**Comment by AllSpeeds** [comment]
UPDATE: not sure I'll get to the additional test today. The match event will not fire more than once because the boolean would not be set for matched in emitEvaluationEvent and therefore not pass the check, if(matched).

**Pull request closed without merging**
